###***************************************************************************###

### Dashboard: Event Handlers ###

###***************************************************************************###

Template.Dashboard.events {

}

###***************************************************************************###

### Dashboard: Helpers ###

###***************************************************************************###

Template.Dashboard.helpers {}

###***************************************************************************###

### Dashboard: Lifecycle Hooks ###

###***************************************************************************###

Template.Dashboard.created = ->

Template.Dashboard.rendered = ->
  console.log "template Dashboard rendered"
  console.log "@", @
  # Donut chart
  nv.addGraph () ->
    chart = nv.models.pieChart()
        .x((d) -> return d.label )
        .y((d) -> return d.value )
        .showLabels(true)     #Display pie labels
        .labelThreshold(.05)  #Configure the minimum slice size for labels to show up
        .labelType("percent") #Configure what type of data to show in the label. Can be "key", "value" or "percent"
        .donut(true)          #Turn on Donut mode. Makes pie chart look tasty!
        .donutRatio(0.35)     #Configure how big you want the donut hole size to be.

    d3.select("#chart svg")
        .datum(exampleData())
        .transition().duration(350)
        .call(chart);

    chart


  # Pie chart example data. Note how there is only a single array of key-value pairs.
  exampleData = ()->
    [
      { 
        "label": "One",
        "value" : 29.765957771107
      } , 
      { 
        "label": "Two",
        "value" : 0
      } , 
      { 
        "label": "Three",
        "value" : 32.807804682612
      } , 
      { 
        "label": "Four",
        "value" : 196.45946739256
      } , 
      { 
        "label": "Five",
        "value" : 0.19434030906893
      } , 
      { 
        "label": "Six",
        "value" : 98.079782601442
      } , 
      { 
        "label": "Seven",
        "value" : 13.925743130903
      } , 
      { 
        "label": "Eight",
        "value" : 5.1387322875705
      }
    ]

Template.Dashboard.destroyed = ->

# ---
# generated by js2coffee 2.0.1